server:
  port: 8080

spring:
  application:
    name: Spring-Security
  datasource:
    url: jdbc:h2:mem:securitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

security:
  jwt:
    token:
      secret-key: "khgfjdkhg45345djfhgkdhguytit4yfdss34yt49hrughkdjfhgkfdhgdkfhgkddas"
      # 1 days: 1000*60*60*24
      expiration: 86400000
      # 2 days
      refresh_expiration: 172800000
